CREATE TABLE "team_sync_ai_ts_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "team_sync_ai_ts_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "team_sync_ai_ts_ai_prompt_version" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "team_sync_ai_ts_ai_prompt_version_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"promptId" integer NOT NULL,
	"version" integer NOT NULL,
	"promptTemplate" text NOT NULL,
	"systemInstruction" text,
	"changeNotes" text,
	"isActive" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "team_sync_ai_ts_api_metric" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "team_sync_ai_ts_api_metric_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"service" varchar(120) NOT NULL,
	"processingTimeMs" integer,
	"inputTokens" integer,
	"outputTokens" integer,
	"totalCost" numeric(12, 6),
	"wasCache" boolean DEFAULT false NOT NULL,
	"hadError" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "team_sync_ai_ts_cache_metric" (
	"service" varchar(120) NOT NULL,
	"inputHash" varchar(128) NOT NULL,
	"hitCount" integer DEFAULT 0 NOT NULL,
	"missCount" integer DEFAULT 0 NOT NULL,
	"lastAccessedAt" timestamp with time zone NOT NULL,
	CONSTRAINT "team_sync_ai_ts_cache_metric_service_inputHash_pk" PRIMARY KEY("service","inputHash")
);
--> statement-breakpoint
CREATE TABLE "team_sync_ai_ts_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "team_sync_ai_ts_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "team_sync_ai_ts_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "team_sync_ai_ts_team_sync_company" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "team_sync_ai_ts_team_sync_company_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"industry" varchar(255) NOT NULL,
	"businessIntent" text NOT NULL,
	"technologyIntent" text NOT NULL,
	"standards" text[] NOT NULL,
	"partnerships" text[] NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "team_sync_ai_ts_team_sync_project" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "team_sync_ai_ts_team_sync_project_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"companyId" integer NOT NULL,
	"projectName" varchar(255) NOT NULL,
	"summary" text NOT NULL,
	"requiredCapabilities" text[] NOT NULL,
	"requiredTechStack" text[] NOT NULL,
	"riskFactors" text[] NOT NULL,
	"targetTeamSize" integer NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "team_sync_ai_ts_team_sync_talent_member" (
	"id" varchar(64) PRIMARY KEY NOT NULL,
	"fullName" varchar(255) NOT NULL,
	"role" varchar(128) NOT NULL,
	"expertise" text[] NOT NULL,
	"techStack" text[] NOT NULL,
	"certifications" text[] NOT NULL,
	"capacityPercent" integer NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "team_sync_ai_ts_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "team_sync_ai_ts_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "team_sync_ai_ts_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "team_sync_ai_ts_account" ADD CONSTRAINT "team_sync_ai_ts_account_userId_team_sync_ai_ts_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."team_sync_ai_ts_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "team_sync_ai_ts_post" ADD CONSTRAINT "team_sync_ai_ts_post_createdById_team_sync_ai_ts_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."team_sync_ai_ts_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "team_sync_ai_ts_session" ADD CONSTRAINT "team_sync_ai_ts_session_userId_team_sync_ai_ts_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."team_sync_ai_ts_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "team_sync_ai_ts_team_sync_project" ADD CONSTRAINT "team_sync_ai_ts_team_sync_project_companyId_team_sync_ai_ts_team_sync_company_id_fk" FOREIGN KEY ("companyId") REFERENCES "public"."team_sync_ai_ts_team_sync_company"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "team_sync_ai_ts_account" USING btree ("userId");--> statement-breakpoint
CREATE UNIQUE INDEX "ai_prompt_version_prompt_version_uq" ON "team_sync_ai_ts_ai_prompt_version" USING btree ("promptId","version");--> statement-breakpoint
CREATE INDEX "ai_prompt_version_prompt_id_idx" ON "team_sync_ai_ts_ai_prompt_version" USING btree ("promptId");--> statement-breakpoint
CREATE INDEX "api_metric_service_idx" ON "team_sync_ai_ts_api_metric" USING btree ("service");--> statement-breakpoint
CREATE INDEX "api_metric_created_at_idx" ON "team_sync_ai_ts_api_metric" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "cache_metric_last_access_idx" ON "team_sync_ai_ts_cache_metric" USING btree ("lastAccessedAt");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "team_sync_ai_ts_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "team_sync_ai_ts_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "team_sync_ai_ts_session" USING btree ("userId");--> statement-breakpoint
CREATE UNIQUE INDEX "team_sync_company_name_uq" ON "team_sync_ai_ts_team_sync_company" USING btree ("name");--> statement-breakpoint
CREATE INDEX "team_sync_project_company_idx" ON "team_sync_ai_ts_team_sync_project" USING btree ("companyId");--> statement-breakpoint
CREATE UNIQUE INDEX "team_sync_project_name_uq" ON "team_sync_ai_ts_team_sync_project" USING btree ("projectName");--> statement-breakpoint
CREATE INDEX "team_sync_talent_member_role_idx" ON "team_sync_ai_ts_team_sync_talent_member" USING btree ("role");